version: "3.7"

services:
  ipfs:
    ports:
      - 5001:5001
      - 8080:8080

  lotus:
    image: textile/lotus-devnet:v0.4.0
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=1500
      - TEXLOTUSDEVNET_BIGSECTORS=${BIGSECTORS}
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
